import type { Metadata } from "next";
import { Inter, Atkinson_Hyperlegible } from "next/font/google";
import "./globals.css";
import { GoogleAnalytics } from "@next/third-parties/google";

const inter = Inter({ subsets: ["latin"] });
const atkinson = Atkinson_Hyperlegible({
  weight: "700", // Choix entre "400" et "700" en fonction de la graisse souhaitée pour la police.
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quiz - Ensemble contre le sexisme",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
      <GoogleAnalytics gaId="G-JF73GETG80" />
    </html>
  );
}
